import { Inter, Encode_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import theHead from "./img/header.png"
import theheadephone from "./img/headphoneview.png"
import footerpic from './img/headphoneview.png'
import foot1 from './img/foot1.png'
import foot2 from './img/foot2s.png'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "United Bank for Africa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
       {/* <Header/> */}
        
        <div className="bg-white ">
        {children}
        </div>
       
    
        </body>
    </html>
  );
}
